name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "labeled", "unlabeled"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x

      - name: install dependencies
        run: pnpm i

      - name: run test script
        run: npm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
